baseURL = 'https://michael-huelsen.de/'
languageCode = 'de-DE'
title = 'michael-huelsen.de'
theme = 'papermod'
description = 'Personal website of Michael Hülsen'
copyright = '© 2015-2025 by Michael Hülsen'

### some configuration
pluralizeListTitles = false

### MENUS
# sectionPagesMenu = 'main'
sectionPagesMenu = 'more'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 5
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 7
  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 50
  [[menus.main]]
    name = 'Blogroll'
    pageRef = '/blogroll'
    weight = 60
  [[menus.main]]
    name = 'More...'
    pageRef = '/more'
    weight = 70

defaultContentLanguage = 'de'
defaultContentLanguageInSubdir = true

[languages.de]
contentDir = 'content/de'
languageCode = 'de-DE'
languageName = 'German'
weight = 1

[languages.en]
contentDir = 'content/en'
languageCode = 'en-US'
languageName = 'English'
weight = 2

ignoreFiles = ['IDEAS.md', 'README.md', 'LICENSE', 'changelog.component.ts']

[taxonomies]
tag = "tags"
category = "categories"

[params]
  copyright-year = '2015-2025'
  # subtitle = ''
  [params.author]
    email = 'mail@michael-huelsen.de'
    name = 'Michael Hülsen'
